
import { NextRequest, NextResponse } from "next/server";
import fs from "fs";
import path from "path";

export async function GET(request: NextRequest) {
  try {
    const searchParams = request.nextUrl.searchParams;
    const filename = searchParams.get("file");

    if (!filename) {
      return NextResponse.json({ error: "No file provided" }, { status: 400 });
    }

    // Path to the 'final' JSON generated by the Decision Engine in the shared volume
    // web/app/api/poll -> web -> root -> backend -> agents -> data -> [file].final.json
    const backendDataDir = path.resolve(process.cwd(), "..", "gitverified-backend", "agents", "data");
    const finalResultPath = path.join(backendDataDir, `${filename}.final.json`);

    if (fs.existsSync(finalResultPath)) {
        const content = await fs.promises.readFile(finalResultPath, "utf-8");
        const json = JSON.parse(content);
        return NextResponse.json({ 
            status: "complete", 
            data: json 
        });
    } else {
        // Check if error file exists? Or just pending.
        return NextResponse.json({ status: "running" });
    }

  } catch (error) {
    console.error("Poll Error:", error);
    return NextResponse.json({ error: "Poll failed" }, { status: 500 });
  }
}
