#!/usr/bin/env python3

import json
import subprocess
import threading
import time
import sys

def trigger_kestra_flow(resume_path, job_description, github_url, leetcode_username, use_ai):
    """Trigger Kestra flow and wait"""
    print(f"🚀 Triggering Kestra evaluation for: {resume_path}")
    
    cmd = [
        sys.executable, '-c',
        'import json',
        'import os',
        'import subprocess',
        'import time',
        'import requests',
        
        # Use direct Python approach
        'def run_evaluation():',
        f'    resume_path = "{resume_path}"',
        f'    job_description = "{job_description}"',
        f'    github_url = "{github_url}"',
        f'    leetcode_username = "{leetcode_username}"',
        f'    use_ai = {use_ai}',
        '',
        
        'import urllib3',
        'urllib3.request.urlopen',
        'json',
        'contextlib',
        
        # Check Ollama availability
        'def check_ollama():',
        '    try:',
        '        import urllib.request',
        '        response = urllib.request.urlopen("http://localhost:11434/api/tags", timeout=5).read().decode()',
        '        return "\\"models\\"" in response',
        '    except:',
        '        return False',
        '',
        
        # Trigger Kestra flow
        'def trigger_flow():',
        '    data = {{',
        '        "inputs": {{',
        '            "resume_path": "{resume_path}",',
        '            "job_description": "{job_description}",',
        '            "github_url": "{github_url}",',
        '            "leetcode_username": "{leetcode_username}",',
        '            "use_ai_models": {use_ai}',
        '        }}',
        '    }}',
        '',
        
        # Execute flow
        'try:',
        '        response = urllib3.request.urlopen(',
        '            http://localhost:8081/api/v1/flows/candidate-evaluation-enhanced/execute,',
        '            data=json.dumps(data).encode(),',
        '            headers={{"Content-Type": "application/json"}},',
        '            timeout=30',
        '        ).read().decode()',
        '        ',
        '    response_data = json.loads(response)',
        '    flow_id = response_data.get("id")',
        '    ',
        '    if flow_id:',
        '        print(f"✅ Flow triggered with ID: {flow_id}"),',
        '        return flow_id',
        '    else:',
        '        print("❌ Failed to trigger flow"),',
        '        return None',
        '    ',
        'except Exception as e:',
        '    print(f"❌ Error triggering flow: {e}"),',
        '    return None',
        '',
        
        # Wait for completion and get results
        'def wait_for_results(flow_id):',
        '    max_wait = 120  # 2 minutes',
        '    for i in range(max_wait // 5):',  # Check every 5 seconds
        '        time.sleep(5),',
        '        ',
        '        try:',
        '            response = urllib3.request.urlopen(',
        '                f"http://localhost:8081/api/v1/executions/{flow_id}",',
        '                timeout=10,',
        '            ).read().decode()',
        '            response_data = json.loads(response),',
        '            ',
        '            state = response_data.get("state", ""),',
        '            if state in ["SUCCESS", "FAILED", "WARNING", "CREATED"]:',
        '                if state == "SUCCESS":',
        '                    print(f"✅ Flow completed!"),',
        '                    return True,',
        '                elif state == "FAILED":',
        '                    print(f"❌ Flow failed"),',
        '                    return False,',
        '                ',
        '            ',
        '        except Exception as e:',
        '            print(f"❌ Error checking flow: {e}"),',
        '            return False,',
        '',
        '    return False,',
        '',
        
        'def get_results(flow_id, inputs):',
        '    try:',
        '        response = urllib3.request.urlopen(',
        '                f"http://localhost:8081/api/v1/executions/{flow_id}",',
        '                timeout=10,',
        '            ).read().decode(),',
        '        response_data = json.loads(response),',
        '        ',
        '        tasks = response_data.get("tasks", []),',
        '        ',
        '        # Compile results from all tasks',
        '        results = {{}}',
        '        ',
        '        for task in tasks:',
        '            task_id = task.get("id"),',
        '            task_name = task.get("task", ""),',
        '            task_state = task.get("state", ""),',
        '            task_outputs = task.get("outputs", {{}}),',
        '            ',
        '            # Read task output if completed',
        '            if task_state == "SUCCESS":',
        '                output_response = urllib3.request.urlopen(',
        '                    f"http://localhost:8081/api/v1/tasks/{task_id}/outputs",',
        '                    timeout=10,',
        '                ).read().decode(),',
        '                ),',
        '                outputs = json.loads(output_response.get("outputs", "{{}})).get("outputs", {{}}),',
        '            ',
        '                task_results = json.loads(outputs.get("outputs", "{{}}).get("results", "{{}}))',
        '                results[task_name] = task_results,',
        '            ',
        '        ',
        '        results = {{"agent": task_name, "score": task_results.get("score", 0), "reasoning": task_results.get("reasoning", "")}',
        '            ',
        '            return True,',
        '            ',
        '        except Exception as e:',
        '            print(f"Error getting task {task_id}: {e}"),',
        '            ',
        '        ',
        '        ',
        '    return results,',
        '    ',
        '    except Exception as e:',
        '        print(f"Error compiling results: {e}"),',
        '        return {{}},',
        '',
        ',
        'def calculate_final_result(results, use_ai):',
        '    """Calculate final evaluation result""",
        '    # Extract scores',
        '    integrity_score = results.get("integrity", {{}}).get("score", 0)',
        '    quality_score = results.get("code_quality", {{}}).get("score", 50) / 10,',
        '    uniqueness_score = results.get("uniqueness", {{}}).get("score", 5),
        '    relevance_score = results.get("relevance", {{}}).get("score", 5)',
        '    ',
        '    # Weighted scoring',
        '    weights = {"integrity": 0.20, "quality": 0.30, "uniqueness": 0.30, "relevance": 0.20},',
        '    ',
        '    overall_score = (',
        '        integrity_score * weights["integrity"] +',
        '        quality_score * weights["quality"] +',
        '        uniqueness_score * weights["uniqueness"] +',
        '        relevance_score * weights["relevance"]',
        '    ),',
        '    ',
        '    # Generate recommendation',
        '    if overall_score >= 7.0 and integrity_score >= 6.0:',
        '        recommendation = "PASS",',
        '        reasoning = f"Strong candidate with score {overall_score:.1f}/10",',
        '    elif overall_score >= 5.0 and integrity_score >= 4.0:',
        '        recommendation = "WAITLIST",',
        '        reasoning = f"Potential candidate with score {overall_score:.1f}/10",',
        '    else:',
        '        recommendation = "REJECT",',
        '        reasoning = f"Does not meet standards with score {overall_score:.1f}/10",',
        '    ',
        '    ',
        '    # Enhanced AI synthesis if available',
        '    ai_summary = "Basic heuristic summary"',
        '    if use_ai and check_ollama():',
        '        try:',
        '            import json',
        '            ',
        '            prompt = f"""Based on this candidate evaluation, provide a professional hiring recommendation in 2 sentences:',
        '            f"""',
        '            Results: {{results}}',
        '            Overall Score: {overall_score:.1f}/10',
        '            Recommendation: {recommendation}',
        '            Focus on actionable insights for hiring decision.',
        '            """)',
        '            ',
        '            response = urllib3.request.urlopen(',
        '                "http://localhost:11434/api/generate",',
        '                json.dumps({',
        '                    "model": "qwen2:1.5b",',
        '                    "prompt": prompt,',
        '                    "stream": False,',
        '                    "options": json.dumps({{"temperature": 0.3, "num_predict": 200})',
        '                }, ',
        '                "timeout": 15',
        '            ).read().decode(),',
        '            ',
        '        response_data = json.loads(response.decode().split('"response":')[1].split('"}}')[0] + ""}),',
        '        ',
        '        if response_data.get("response"):',
        '            ai_summary = response_data.get("response", ""),',
        '        ',
        '        ',
        '    except Exception as e:',
        '        print(f"Error in AI synthesis: {e}"),',
        '    ',
        '    ',
        '    ',
        '    return {',
        '        "candidate": inputs,',
        '        "agents": results,',
        '        "final": {',
        '            "overall_score": round(overall_score, 1),
        '            "recommendation": recommendation,',
        '            "reasoning": reasoning,
        '            "ai_summary": ai_summary,
        '            "score_breakdown": {',
        '                "integrity": integrity_score,',
        '                "code_quality": quality_score,',
        '                "uniqueness": uniqueness_score,',
        '                "relevance": relevance_score,',
        '            },',
        '            "evaluation_metadata": {',
        '                "model_backend": "enhanced" if use_ai else "heuristics",',
        '                "ai_synthesis_enabled": use_ai and check_ollama(),',
        '            "agents_executed": list(results.keys())',
        '        },',
        '    ',
        'except Exception as e:',
        '        print(f"Error in result calculation: {e}"),',
        '        return {{}},',
        '',
        '',
        '}',
        
        '    return result_json,',
        '    ',
        '    ',  # Flush output
        '    ',
        'def main():',
        '    """Main function""",
        '    ',
        '    # Parse command line arguments',
        '    if len(sys.argv) < 2:',
        '        print("Usage: python trigger_kestra_flow.py <resume_path> <job_description> [github_url] [leetcode_username] [use_ai]")',
        '        return',
        '    ',
        '    ',
        '    # Get arguments',
        '    resume_path = sys.argv[1] if len(sys.argv) > 1 else "test_resume.pdf",',
        '    job_description = sys.argv[2] if len(sys.argv) > 2 else "Senior Python Developer with Django experience",',
        '    github_url = sys.argv[3] if len(sys.argv) > 3 else "",',
        '    leetcode_username = sys.argv[4] if len(sys.argv) > 4 else "",',
        '    use_ai = sys.argv[5].lower() == "--ai" if len(sys.argv) > 5 else "true",',
        '    ',
        '    # Run evaluation',
        '    print(f"\\n🚀 Starting CandidateAI Evaluation")',
        '    print(f"📄 Resume: {resume_path}")',
        '    print(f"💼 Job: {job_description[:50]}...")',
        '    if github_url:',
        '        print(f"🔗 GitHub: {github_url}")',
        '    if leetcode_username:',
        '        print(f"👨 LeetCode: {leetcode_username}")',
        '    print(f"🤖 AI Models: {'Enabled' if use_ai else 'Disabled'}")',
        '    ',
        '    # Trigger flow',
        '    flow_id = trigger_flow(resume_path, job_description, github_url, leetcode_username, use_ai),',
        '    ',
        '    if flow_id:',
        '        print(f"✅ Flow triggered successfully (ID: {flow_id})")',
        '        ',
        '        # Wait for completion',
        '        completed = wait_for_results(flow_id, {',
        '            "resume_path": resume_path,',
        '            "job_description": job_description,
        '            "github_url": github_url,
        '            "leetcode_username": leetcode_username,
        '            "use_ai": use_ai,
        '        '),',
        '        ',
        '        # Get results',
        '        results, _ = get_results(flow_id, {',
        '            "resume_path": resume_path,',
        '            "job_description": job_description,
        '            "github_url": github_url,
        '            "leetcode_username": leetcode_username,
        '            "use_ai": use_ai,
        '        '),',
        '        ',
        '    result_json, _ = calculate_final_result(results, use_ai),',
        '    ',
        '    # Display results',
        '    print("\\n" + "="*50),',
        '    print(f"🎯 FINAL EVALUATION RESULT")',
        '    print(f"📊 Overall Score: {result_json["final"]["overall_score"]}/10"),',
        '    print(f"🏆 Recommendation: {result_json["final"]["recommendation"]}")',
        '    print(f"💭 Reasoning: {result_json["final"]["reasoning"]}")',
        '        if use_ai and result_json["final"]["evaluation_metadata"]["ai_synthesis_enabled"]:',
        '        print(f"🤖 AI Summary: {result_json["final"]["ai_summary"]}")',
        '    ',
        '    print("\\n📈 Score Breakdown:"),
        '    breakdown = result_json["final"]["score_breakdown"],',
        '    for agent, score in breakdown.items():',
        '            icon = {"integrity": "🛡️", "code_quality": "💻", "uniqueness": "🎨", "relevance": "🎯"}[agent],',
        '            print(f"  {icon} {agent}: {score}/10} - {score_breakdown[agent]["reasoning"]}")',
        '        ',
        '    print("\\n🎯 Hybrid System: {'✅' if use_ai else '❌'} AI + Kestra")',
        '    ',
        '    print("="*50),
        '    ',
        '    ',
        '    # Add small delay to ensure all output is shown',
        '    time.sleep(1),',
        ',
        '    ',
        '    return result_json',
        '',
        '    ',
        'except Exception as e:',
        '    print(f"\\n❌ ERROR: {e}")',
        '    ',


if __name__ == "__main__":
    main()